server:
  workers: 1
  node:
    environment: production
  log:
    trino:
      level: WARN
  config:
    http-server.process-forwarded: true
    query:
      maxMemory: "4GB"
  autoscaling:
    enabled: false
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 80
coordinator:
  config:
    http-server.process-forwarded: "true"
  jvm:
    maxHeapSize: "1G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"
worker:
  config:
    http-server.process-forwarded: "true"
  jvm:
    maxHeapSize: "2G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"
additionalConfigProperties:
  - http-server.process-forwarded=true
catalogs:
  #  wh01: |
  #    connector.name=iceberg
  #    iceberg.catalog.type=nessie
  #    iceberg.file-format=PARQUET
  #    iceberg.nessie-catalog.uri=http://nessie05:19120/api/v2
  #    iceberg.nessie-catalog.ref=main
  #    iceberg.nessie-catalog.default-warehouse-dir=s3://wh01/
  #    iceberg.register-table-procedure.enabled=true
  #    iceberg.query-partition-filter-required=true
  #    iceberg.object-store-layout.enabled=true
  #    iceberg.remove-orphan-files.min-retention=1d
  #    fs.native-s3.enabled=true
  #    s3.endpoint=http://minio02:9000
  #    s3.path-style-access=true
  #    s3.region=us-west-2
  #    s3.aws-access-key=admin
  #    s3.aws-secret-key=aciiHJsbJh
  wh02: |
    connector.name=iceberg
    iceberg.catalog.type=rest
    iceberg.file-format=PARQUET
    iceberg.rest-catalog.uri=http://nessie05:19120/iceberg
    iceberg.rest-catalog.warehouse=s3://wh02/
    iceberg.register-table-procedure.enabled=true
    iceberg.query-partition-filter-required=false
    iceberg.object-store-layout.enabled=true
    iceberg.remove-orphan-files.min-retention=1d
    fs.native-s3.enabled=true
    s3.endpoint=http://minio02:9000
    s3.path-style-access=true
    s3.region=us-west-2
    s3.aws-access-key=admin
    s3.aws-secret-key=aciiHJsbJh
  db02: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://pg01-cluster-rw:5432/db02
    connection-user=role02
    connection-password=password
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: trino.local
      paths:
        - path: /
          pathType: ImplementationSpecific