image:
  tag: latest
replicaCount: 1
logLevel: INFO
usePasswordFiles: false
## @param versionStoreType Set version store type. The chart natively supports JDBC_POSTGRESQL, ROCKSDB and IN_MEMORY. Any other type requires you to add the configuration in configOverrides and secretConfigOverrides.
versionStoreType: IN_MEMORY
startupProbe:
  enabled: true
ingress:
  enabled: true
  selfSigned: false
  pathType: ImplementationSpecific
  hostname: nessie.local
  path: /
  ingressClassName: "nginx"
  tls: false
persistence:
  enabled: true
serviceAccount:
  create: true
postgresql:
  enabled: false
#externalDatabase:
#  host: "pg01-cluster-rw"
#  port: 5432
#  user: role02
#  database: nessiedb
#  existingSecret: "role02-secret"
#  existingSecretPasswordKey: "password"
